BSP-2956 Add lesshint linting
perfectsense/brightspot-styleguide pull request #78
Opened 2017-01-25 20:28 UTC by rhino88

This PR adds less linting configured by the `.lesshintrc`. Each enabled linter is explicitly marked as an "error" instead of a warning. For traceability, even default lesshint values are explicitly stated in the `.lesshintrc`.

Example output:

![image](https://cloud.githubusercontent.com/assets/1299507/22307707/1b037eb2-e312-11e6-9f1e-b1d2f3a3f55a.png)

The [current gulp-lesshint feature](https://github.com/lesshint/gulp-lesshint/blob/master/index.js#L110) to fail a build on error only provides information on how many errors were detected, and does not provide information on individual errors. A subsequent PR will look to create a custom reporter for this, use lesshint directly, or use gulp-plumber to provide better error output and failure.

References: [18f styleguide](https://pages.18f.gov/frontend/ ), [Airbnb styleguide](https://github.com/airbnb/css)

2017-01-26 17:18 UTC, jpencola requested changes

2017-01-26 17:18 UTC, jpencola commented on js/task/lint.js
> +          configPath: path.join(
Minor nitpick: Please flatten this down to a single-line for consistency

2017-01-27 15:32 UTC, jpencola approved these changes

2017-01-30 16:38 UTC, jpencola reviewed
@rhino88 What do you think about bumping up the maxCharPerLine to `100`?

2017-01-30 16:40 UTC, jpencola reviewed
@rhino88 Using our container-query approach, I think it's going to be common to go beyond 3 levels deep. What do you think about bumping depthLevel up to `4`?

2017-01-30 16:41 UTC, trhoppe commented
Won't the 3 levels deep be inside the mixing and not in the container query?

2017-01-30 18:03 UTC, jpencola reviewed
@trhoppe You're right, it seems that the linter doesn't add up the level(s) the mix-in is being used within.

2017-01-30 20:24 UTC, rhino88 commented
Increased maxCharPerLine to 100

2017-01-31 14:37 UTC, jpencola commented
@rhino88 / @trhoppe After running this against the Express codebase and discussing the potential for depth levels > 3 when using `extend`, I've increased the depthLevel to 5.

2017-02-01 15:53 UTC, jpencola commented
@rhino88 I'm seeing the linter report a `depthLevel` error:
`There shouldn't be more than '5' levels deep from the style's parent, check the children's depth`
 given this selector:

```less
.Foo {
    &-one {
        color: red;
    }

    &-two {
        color: red;
    }

    &-three {
        color: red;
    }

    &-four {
        color: red;
    }

    &-five {
        color: red;
    }
}
```

Do you notice this too?

2017-02-01 22:58 UTC, rhino88 commented
Temporarily disabled the depth level check. Hoping we can open a github issue and reenable later.

2017-02-07 19:39 UTC, merged