BSP-2947 Improve JS debugging on latest styleguide
perfectsense/brightspot-styleguide pull request #93
Opened 2017-02-24 18:30 UTC by mlikouris

if the env.JS_MIN doesn't equal true then its copying All.js to All.min.js

2017-02-27 20:24 UTC, jpencola requested changes

2017-02-27 20:24 UTC, jpencola commented on js/task/watch.js
> +/* eslint-disable no-unused-vars */
Escape the linter only on the LOC where it's needed

2017-02-27 20:24 UTC, jpencola commented on js/task/watch.js
> +const path = require('path')
Reorder the imports alphabetically

2017-02-27 20:30 UTC, mlikouris commented on js/task/watch.js
> +const path = require('path')
gulp-load-plugins, comes before path. ;)

2017-03-14 19:23 UTC, jpencola approved these changes

2017-03-14 19:48 UTC, jpencola requested changes

2017-03-14 19:48 UTC, jpencola commented on js/task/watch.js
> +          logger.info(`COPY .js >> .min.js: ${event.path}`)
I think this log message should be removed because it makes the watcher log too verbose.

2017-03-14 20:07 UTC, jpencola approved these changes
💯

2017-05-02 14:46 UTC, closed without merging